# Generated by Django 5.1 on 2024-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coffee', 'コーヒー'), ('espresso', 'エスプレッソ'), ('oleato', 'オリアート'), ('frappuccino', 'フラペチーノ'), ('tea', 'ティー'), ('others', 'その他')], default='coffee', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
        ),
    ]
